### ISSUE TITLE
Add faces

### ISSUE THREAD

**Issue by dosbenzos** [maidi29/custom-avatar-generator#1]
Hey. 
Are you planning on adding the faces soon?

**Comment by maidi29** [comment]
Hey @dosbenzos 
Thanks for your feature request.
I didn't plan it, because I think it looks minimalistic and stylish ;) but I can add a property to enable the faces. I will implement it in the next days!

**Comment by dosbenzos** [comment]
Hey maidi

Thank you very much.
I am looking for an epic component like yours. One with all details would
be perfect! (You have the svg from the getavataars.com library)

I am looking foreward to the update.

BR and much love from switzerland
Dosbenzos

maidi29 ***@***.***> schrieb am Fr., 16. Juli 2021, 13:36:

**Comment by maidi29** [comment]
Hey @dosbenzos 

sorry for the long waiting time. I added most of the face details from getavataars.com library.
You can enable it by setting the attribute "enable-face" to true (see https://github.com/maidi29/custom-avatar-generator/blob/main/README.md).
Check out the demo here: https://htmlpreview.github.io/?https://github.com/maidi29/custom-avatar-generator/demo/demo/demo-with-face.html
Tell me if you need something else. You are also welcome to contribute to this repository and create a pull request :)

Greets from germany
